apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-pod-affinity
  labels:
    app: spring-music
    tier: frontend
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spring-music
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
      - name: spring-music
        image: yanivomc/spring-music:latest
        
---     
apiVersion: v1     
kind: Service      # Create new service
metadata:
  name: my-service # Name of the service
spec:
  selector:
    app: spring-music    # Run on any pod(s) with label - app: myapp
  ports:          # Map incoming port to target port
  - name: http-web    # Setting multiple ports listterns 
    protocol: TCP
    port: 80
    targetPort: 9376
  - name: https-managment
    protocol: TCP
    port: 443
    targetPort: 9388
  type: LoadBalancer
